### ISSUE TITLE
smoothState's domain is now used to distribute malware

### ISSUE THREAD

**Issue by ghost** [innoq/ROCA#36]
I suppose the owner has allowed it to expire, so perhaps remove _smoothstate.com_ altogether. Replacing it with [https://github.com/miguel-perez/smoothState.js](https://github.com/miguel-perez/smoothState.js) might be preferable.

**Comment by mvitz** [comment]
Thanks, for the hint. This was fixed in 4e175db931702553357740b80916519ccf9a7bf4
